# Generated by Django 5.0.3 on 2024-03-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.TextField(choices=[('cuidados', 'Cuidado'), ('trabajo_manual', 'Trabajo manual'), ('mascotas', 'Mascotas'), ('otros', 'Otros')])),
            ],
        ),
    ]
