# Generated by Django 5.0.3 on 2024-03-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service1', to='services.service')),
                ('service2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service2', to='services.service')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='users.customuser')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='users.customuser')),
            ],
        ),
    ]
